name: Publish Docker Image to Docker Hub

on:
  push:
    tags:
      - '*'  # Déclencheur pour les tags versionnés

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract tag name
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/squid:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/squid:latest
            
          platforms: linux/amd64,linux/arm64,linux/arm/v7
